# Generated by Django 5.0.3 on 2024-09-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=70)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.TextField()),
                ('cast', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=60)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('language', models.CharField(max_length=60)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('movie_video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('customer_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now=True)),
                ('review', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serial_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('customer_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now=True)),
                ('review', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('duration', models.TimeField()),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('episode', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('months', models.IntegerField()),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('cast', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('director', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('webseries_video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Webseries_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('customer_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now=True)),
                ('review', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Serials_Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='episodes/')),
                ('description', models.TextField()),
                ('episode_number', models.IntegerField()),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalottapp.serials')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('holder_name', models.CharField(max_length=100)),
                ('card_number', models.BigIntegerField()),
                ('cvv_number', models.BigIntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalottapp.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('episode_number', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('thumbnail', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('webseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalottapp.webseries')),
            ],
        ),
    ]
