# Generated by Django 5.0.3 on 2024-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalottapp', '0002_alter_customer_enddate_alter_customer_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='duration',
            field=models.DurationField(),
        ),
    ]
