# Generated by Django 5.0.3 on 2024-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalottapp', '0003_alter_serials_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials_episodes',
            name='thumbnail',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
