# Generated by Django 5.0.3 on 2024-09-06 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalottapp', '0005_movie_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial_review',
            name='serial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digitalottapp.serials'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webseries_review',
            name='web_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digitalottapp.webseries'),
            preserve_default=False,
        ),
    ]
